version: "3.8"

services:
  postgres:
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=telegram_bot_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
